name: Demo
on:
  push: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make library
        run: make
      - name: Compile testing system
        run: gcc testing_system/testing_system.c -o testing_system/run -w
      - name: Execute tests
        run: ./testing_system/run 1>/dev/null
